blank_issues_enabled: false
contact_links:
  - name: Translations
    url: https://github.com/breezy-weather/breezy-weather#translation-improvements
    about: New translation, update to existing translations
  - name: Questions
    url: https://github.com/breezy-weather/breezy-weather/discussions/categories/q-a
    about: Ask the community for help