blank_issues_enabled: false
contact_links:
  - name: Translations
    url: https://github.com/breezy-weather/breezy-weather#translation-improvements
    about: New translation, update to existing translations