name: Issue labeled

on:
  issues:
    types: [labeled]

permissions:
  contents: read

jobs:
  issueLabeled:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Add undecided comment
        uses: peter-evans/create-or-update-comment@v4
        if: ${{ github.event.label.name == 'Undecided' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: >
            This issue has been put aside. It is currently unclear if it will ever be implemented as it seems to cover too narrow of a use case or doesn’t seem to fit into Breezy Weather.

            Please try to clarify the use case or consider proposing something more generic to make it useful to more users.
